version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: unless-stopped

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    restart: on-failure
    expose:
      - "9000"

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    ports:
      - "6379:6379"
    restart: always
    env_file:
      - .env
    networks:
      - inception

  adminer:
    container_name: adminer
    networks:
      - inception
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"

  ftp:
    container_name: ftp
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    ports:
      - "21:21"
      - "10000-10100:10000-10100"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure

  webstatic:
    container_name: webstatic
    build: ./requirements/bonus/webstatic
    restart: always
    networks:
      - inception

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor/.
    ports:
      - "80:8080"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/thoribal/data/wordpress"

  mariadb_volume:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/thoribal/data/mariadb"

networks:
  inception:
    driver: bridge
